"""Assembles the single-file HTML tearsheet.

Deliberately ordered so that the qualifications come before the numbers. A reader who
stops after the first screen should have seen the leak check and the survivorship warning,
not just a Sharpe ratio. Reports that lead with the headline and bury the caveats in a
footnote are how people talk themselves into strategies.
"""

from __future__ import annotations

import logging
import webbrowser
from datetime import UTC, datetime
from pathlib import Path

import pandas as pd
from jinja2 import Environment, FileSystemLoader, select_autoescape

from .. import __version__
from ..config import Config
from ..validation.ic import ICSummary, quantile_returns
from . import charts

log = logging.getLogger(__name__)

_TEMPLATES = Path(__file__).parent / "templates"


def _env() -> Environment:
    return Environment(
        loader=FileSystemLoader(_TEMPLATES),
        # SVG is generated by matplotlib, not user input, so it is marked safe at the
        # point of insertion; everything else is escaped.
        autoescape=select_autoescape(default_for_string=False, default=False),
        trim_blocks=True,
        lstrip_blocks=True,
    )


def render_tearsheet(
    result,
    cfg: Config,
    *,
    output_path: Path | str,
    ablation=None,
    cost_rows: pd.DataFrame | None = None,
    deflated=None,
    pbo=None,
    portfolio=None,
    feature_importance: pd.Series | None = None,
    block_contribution: dict | None = None,
    benchmark=None,
    run_id: str = "",
    git_revision: str = "",
    extra_caveats: list[str] | None = None,
) -> Path:
    """Write the tearsheet and return its path."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    returns = result.returns
    equity = result.equity

    curves: dict[str, pd.Series] = {}
    if not equity.empty:
        curves[result.name] = equity
    if ablation is not None:
        for name in ("price_only", "momentum", "benchmark"):
            other = ablation.results.get(name)
            if other is not None and name != result.name and not other.equity.empty:
                curves[name] = other.equity
    elif benchmark is not None and not benchmark.equity.empty:
        curves["benchmark"] = benchmark.equity

    ic: ICSummary = result.ic
    deciles = (
        quantile_returns(result.predictions)
        if not result.predictions.empty
        else pd.Series(dtype=float)
    )
    from ..validation.ic import periodic_ic

    ic_series = (
        periodic_ic(result.predictions)
        if not result.predictions.empty
        else pd.Series(dtype=float)
    )

    caveats = list(result.caveats) + list(extra_caveats or [])
    if cfg.universe.assume_survivorship_biased:
        caveats.append(
            "The universe file has no delisting history, so it is a present-day "
            "snapshot. These results are survivorship-biased and optimistic."
        )
    if cfg.data.providers and "synthetic" in cfg.data.providers[:1]:
        caveats.append(
            "Prices came from the synthetic generator. This is a pipeline demonstration, "
            "not a claim about any real market."
        )

    context = {
        "version": __version__,
        "market_name": cfg.market_profile.display_name,
        "generated_at": datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC"),
        "run_id": run_id,
        "git_revision": git_revision,
        "config_hash": cfg.config_hash(),
        "hold_sessions": cfg.calendar.hold_sessions,
        "period_start": str(returns.index[0]) if len(returns) else "n/a",
        "period_end": str(returns.index[-1]) if len(returns) else "n/a",
        "n_weeks": len(returns),
        "m": result.metrics,
        "ic": {
            "mean_ic": ic.mean_ic,
            "t_stat": ic.t_stat,
            "ic_ir": ic.ic_ir,
            "monotonicity": ic.monotonicity,
            "verdict": ic.verdict(),
        },
        "caveats": caveats,
        "verdicts": list(ablation.verdicts) if ablation is not None else [],
        "ablation_rows": (
            ablation.table().to_dict("records") if ablation is not None else []
        ),
        "primary_variant": result.name,
        "news_effect": (
            ablation.news_effect if ablation is not None and ablation.news_effect else None
        ),
        "block_contribution": block_contribution,
        "deflated": deflated.to_dict() | {"verdict": deflated.verdict()} if deflated else None,
        "pbo": pbo.to_dict() if pbo is not None and pbo.is_valid else None,
        "pbo_rows": pbo.table().to_dict("records") if pbo is not None and pbo.is_valid else [],
        "cost_rows": cost_rows.to_dict("records") if cost_rows is not None and not cost_rows.empty else [],
        "equity_svg": charts.equity_chart(curves) if curves else "",
        "drawdown_svg": charts.drawdown_chart(result.drawdown),
        "rolling_sharpe_svg": charts.rolling_sharpe_chart(returns),
        "decile_svg": charts.decile_chart(deciles),
        "ic_svg": charts.ic_chart(ic_series),
        "cost_svg": charts.cost_chart(result.cost_breakdown),
        "short_instrument": cfg.market_profile.short_instrument.value,
    }

    if portfolio is not None and portfolio.positions:
        context["positions"] = [
            {
                "ticker": p.ticker,
                "weight": p.weight,
                "score": p.score,
                "sector": p.sector,
                "instrument": p.instrument,
            }
            for p in sorted(portfolio.positions, key=lambda p: -p.weight)
        ]
        context["entry_session"] = str(portfolio.entry_session)
        context["gross"] = portfolio.gross
        context["net"] = portfolio.net

    if feature_importance is not None and not feature_importance.empty:
        context["top_features"] = [
            {"name": str(name), "importance": float(value)}
            for name, value in feature_importance.head(20).items()
        ]

    html = _env().get_template("tearsheet.html.j2").render(**context)
    output_path.write_text(html)
    log.info("wrote tearsheet to %s (%.0f KB)", output_path, len(html) / 1024)
    return output_path


def render_signal_page(
    portfolio,
    cfg: Config,
    *,
    output_path: Path | str,
    previous_weights: dict[str, float] | None = None,
    orders: pd.DataFrame | None = None,
    warnings: list[str] | None = None,
) -> Path:
    """A compact HTML page for a live weekly signal, without backtest sections."""
    from ..notify.base import format_signal_message

    subject, body = format_signal_message(
        portfolio,
        market=cfg.market_profile.name,
        currency=cfg.market_profile.currency,
        previous_weights=previous_weights,
        warnings=warnings,
    )

    rows = orders.to_html(index=False, border=0) if orders is not None and not orders.empty else ""
    html = f"""<!doctype html><html><head><meta charset="utf-8">
<title>{subject}</title><style>
body{{font:15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
color:#1f2933;max-width:820px;margin:0 auto;padding:40px 28px;}}
h1{{font-size:21px;border-bottom:2px solid #1f2933;padding-bottom:10px;}}
pre{{background:#f7f9fa;padding:16px;overflow-x:auto;font-size:12.5px;line-height:1.5;}}
table{{border-collapse:collapse;width:100%;font-size:13px;margin-top:12px;}}
th{{text-align:right;border-bottom:1.5px solid #1f2933;padding:6px 8px;font-size:10px;
text-transform:uppercase;letter-spacing:.06em;color:#7b8794;}}
td{{text-align:right;border-bottom:1px solid #e4e7eb;padding:5px 8px;}}
th:first-child,td:first-child{{text-align:left;}}
footer{{margin-top:32px;font-size:11.5px;color:#9aa5b1;border-top:1px solid #e4e7eb;padding-top:12px;}}
</style></head><body>
<h1>{subject}</h1>
<pre>{body}</pre>
{('<h2>Orders</h2>' + rows) if rows else ''}
<footer>swingbot {__version__} · config {cfg.config_hash()} ·
Signals only, not investment advice.</footer>
</body></html>"""

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html)
    return output_path


def open_in_browser(path: Path | str) -> None:
    try:
        webbrowser.open(Path(path).absolute().as_uri())
    except Exception as exc:
        log.warning("could not open browser: %s", exc)
